#This is a GitHub workflow file. 
#What happens is that GitHub Actions reads this file and automatically runs the defined tasks whenever the trigger condition is met. 

#First, we set the name of this workflow, which will be shown in the GitHub Actions tab 
name: Build and Push Docker Image 

#Here, we define when this workflow will run 
#We will trigger only on tags like v* (v0, v1, v2, etc.)
#Thus, when we have a tag like "git push origin v1", the pipeline will get triggered 
on: 
  push: 
    tags: 
      - "v*"

#Now we define the actual work we want to do 
#Each job will run on a new virtual machine that GitHub provides 
jobs: 
  #we define the job
  build-and-push: 
    #now we specify the OS of the GitHub-hosted runner 
    runs-on: ubuntu-latest 

    #now we define the list of action this job executes 
    steps: 
      #step 1: checkout the code; this clones the repo into the runner VM so the workflow can access the files 
      - name: Checkout repository 
        uses: actions/checkout@v4 
      
      #setp 2: log in to the Docker Hub; this authenticates to Docker Hub so that images can be pushed later on 
      #we will reference a secret name whose real value is injected at runtime (secrets are masked in logs)
      - name: Log in to Docker Hub 
        uses: docker/login-action@v3
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      #step 3: we extract the metadata; this automatically generates image tags and labels based on the git tag that was triggered 
      - name: Extract Docker metadata 
        id: meta
        uses: docker/metadata-action@v5
        with: 
          #the images are the base name of the Docker Hub image 
          images: ${{ secrets.DOCKERHUB_USERNAME }}/piano-agent 
      
      #setp 4: we build and push the image; this build the Docker image using the Dockerfile and pushes it to Docker Hub in the same step 
      - name: Build and push Docker image 
        uses: docker/build-push-action@v5
        with: 
          #this context tells Docker to use the current directory as the build context 
          context: . 
          dockerfile: Dockerfile 
          push: true 

          #we specify the image tags to apply (these are generated by the metadata step)
          tags: ${{ steps.meta.outputs.tags }}

          #labels are the standard OCI image labels generated by the metadata action 
          #what they do is add metadata to the image 
          labels: ${{ steps.meta.outputs.labels }}